sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
branches:
  only:
    - develop # build develop branch only
script:
  - npm install -g yarn
  - yarn upgrade
  - git clone --depth=1 https://github.com/theme-next/hexo-theme-next.git themes/next
  - git clone --depth=1 https://github.com/theme-next/theme-next-pjax.git themes/next/source/lib/pjax
  - git clone --depth=1 https://github.com/theme-next/theme-next-three.git themes/next/source/lib/three
  - git clone --depth=1 https://github.com/theme-next/theme-next-reading-progress.git themes/next/source/lib/reading_progress
  - git clone --depth=1 https://github.com/theme-next/theme-next-pace themes/next/source/lib/pace
  - hexo clean & hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
