sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: yarn
branches:
  only:
    - develop # build develop branch only

# https://tlvince.com/pandoc-on-travisci
before_install:
  - curl -L https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb > pandoc.deb
  - dpkg -x pandoc.deb .
  - export PATH="$PWD/usr/bin:$PATH"

script:
  - yarn
  - yarn upgrade
  - git clone --depth=1 https://github.com/theme-next/theme-next-pjax.git themes/next/source/lib/pjax
  - git clone --depth=1 https://github.com/theme-next/theme-next-reading-progress.git themes/next/source/lib/reading_progress
  - git clone --depth=1 https://github.com/theme-next/theme-next-pace.git themes/next/source/lib/pace
  - |
    echo "" >> themes/next/layout/_scripts/index.swig
    echo "{%- if theme.mermaid %}
      {% include 'mermaid.swig' %}
    {%- endif %}" >> themes/next/layout/_scripts/index.swig
    echo "" >> themes/next/layout/_scripts/index.swig
    cat source/_data/mermaid.swig >> themes/next/layout/_scripts/mermaid.swig
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: develop
  local-dir: public
